<?php
/**
 * @file
 * os2forms_frontend.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
/**
 * Commented leftover from tro og love erklaering webform
 */
//function os2forms_frontend_user_default_permissions() {
//  $permissions = array();
//
//  // Exported permission: access print.
//  $permissions['access print'] = array(
//    'name' => 'access print',
//    'roles' => array(
//      0 => 'administrator',
//      1 => 'anonymous user',
//      2 => 'authenticated user',
//    ),
//    'module' => 'print',
//  );
//
//  return $permissions;
//}
