<?php
module_load_include('inc', 'bellcom_webform', 'includes/bellcom_webform.xml_generation');
module_load_include('inc', 'bellcom_webform', 'includes/bellcom_webform.settings');

/**
 * Implements hook_menu().
 */
function bellcom_webform_menu() {
  $items = array();

  $items['node/%webform_menu/webform/sbsys_xml'] = array(
    'title' => 'SBSYS XML',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bellcom_webform_sbsys_settings_form', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'includes/bellcom_webform.settings.inc',
    'weight' => 4,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/*
* bellcom_webform_mail_alter: hook_mail_alter
*/
function bellcom_webform_mail_alter(&$message) {
  if (($message['id'] == 'webform_submission') && isset($message['params']['node']) && isset($message['params']['submission'])) {
    $node = $message['params']['node'];
    $submission = $message['params']['submission'];
    $config = bellcom_webform_get_setting($node->nid);
    //$filename = 'sbsys_' . $node->nid . '_' .  $submission->sid . '.xml';
    $filename = 'os2forms.xml';
    if ($config['enabled']) {
      $html_capable = variable_get('webform_email_html_capable', FALSE);
      if ($html_capable) {
        if (module_exists('mimemail')) {
          $attachment = new stdClass;
          $attachment->filecontent = bellcom_webform_module_sbsys_xml($message['params']);
          $attachment->filename = $filename;
          $attachment->filemime = 'text/xml';
          $message['params']['attachments'][] = $attachment;
        }
      }
      else {
        //find existing trenner
        preg_match('/\multipart\/mixed;\ boundary=\"(.*)\"/', $message['headers']['Content-Type'], $matches);
        $trenner = $matches[1];

        //remove message end
        $message['body'][0] = str_replace("--$trenner--", '', $message['body'][0]);

        //and new content
        $message['body'][0] .= "\n\n--" . $trenner . "\n";
        $message['body'][0] .= "Content-Type: text/xml; name=\"$filename\"\n";
        $message['body'][0] .= "Content-Transfer-Encoding: base64\n";
        $message['body'][0] .= "Content-Disposition: attachment; filename=\"$filename\"\n\n";
        $message['body'][0] .= chunk_split(base64_encode(
          bellcom_webform_module_sbsys_xml($message['params'])
        ));
        $message['body'][0] .= "\n\n";
        $message['body'][0] .= "--" . $trenner . "--";
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure that our mail_alter is called AFTER the same hook provided in webform2pdf
 */
function bellcom_webform_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'mail_alter') {
    $group = $implementations['bellcom_webform'];
    unset($implementations['bellcom_webform']);
    $implementations['bellcom_webform'] = $group;
  }
}
