<?php

/**
 * @file
 * Implementation of hook_node_insert().
 */

/**
 * Function fires when a new node is inserted.
 */
function ishoj_dagsorden_aktivitet_node_insert($node) {
  if ($node->type == 'os2web_meetings_meeting') {
    // Opret kun en aktivitet, hvis mødet ikke er en tillægsdagsorden, *
    // da aktiviteten i såfald allerede er blevet oprettet.
    if (!isset($node->field_os2web_meetings_addendum[LANGUAGE_NONE][0]['nid'])) {
      ishoj_dagsorden_aktivitet_opret_ny_node($node);
    }
  }
}

/**
 * Function creates a new node of type 'aktivitet'.
 */
function ishoj_dagsorden_aktivitet_opret_ny_node($n) {

  $node = new stdClass();
  $node->type = 'aktivitet';
  $node->title = $n->title;
  $node->uid = 1;
  node_object_prepare($node);

  // (1 or 0): published or not.
  $node->status = 1;
  // (1 or 0): promoted to front page.
  $node->promote = 1;
  // 0 = comments disabled, 1 = read only, 2 = read/write.
  $node->comment = 0;

  // Overskrift.
  $node->title = "Møde i " . taxonomy_term_load($n->field_os2web_meetings_committee[LANGUAGE_NONE][0]['tid'])->name;

  // Beskrivelse.
  $dagsordenNodePath = "/" . drupal_get_path_alias("node/" . $n->nid);
  $beskrivelse = "<p><a href=\"" . $dagsordenNodePath . "\" title=\"Læs mødets dagsorden\">Læs mødets dagsorden</a></p>";
  if ($n->field_os2web_meetings_location) {
    $beskrivelse .= "<p>" . taxonomy_term_load($n->field_os2web_meetings_location[LANGUAGE_NONE][0]['tid'])->name . "</p>";
  }
  $node->body[und][0]['value'] = $beskrivelse;

  // Aktivitetstype (Termreference).
  $node->field_aktivitetstype[LANGUAGE_NONE][0]['tid'] = 2651;
  // Politik.
  $node->field_aktivitetstype[LANGUAGE_NONE][1]['tid'] = 3128;
  // Dato (Date (Unix timestamp)).
  if (date('I', strtotime($n->field_os2web_meetings_date[LANGUAGE_NONE][0]['value']))) {
    // Sommertid *
    // (7200 seconds = 2 hours).
    $node->field_aktivitetsdato[LANGUAGE_NONE][0]['value']  = strtotime($n->field_os2web_meetings_date[LANGUAGE_NONE][0]['value']) + 7200;
    $node->field_aktivitetsdato[LANGUAGE_NONE][0]['value2'] = strtotime($n->field_os2web_meetings_date[LANGUAGE_NONE][0]['value']) + 7200;
  }
  else {
    // Vintertid.
    // (3600 seconds = 1 hour).
    $node->field_aktivitetsdato[LANGUAGE_NONE][0]['value']  = strtotime($n->field_os2web_meetings_date[LANGUAGE_NONE][0]['value']) + 3600;
    $node->field_aktivitetsdato[LANGUAGE_NONE][0]['value2'] = strtotime($n->field_os2web_meetings_date[LANGUAGE_NONE][0]['value']) + 3600;
  }

  // Aktivitetsstedet bliver angivet ved følgende.
  if (taxonomy_term_load($n->field_os2web_meetings_committee[LANGUAGE_NONE][0]['tid'])->name == "Ishøj Byråd") {
    // Byrådssalen.
    $node->field_aktivitetssted[LANGUAGE_NONE][0]['tid'] = 3201;
  }
  else {
    // Ikke angivet.
    $node->field_aktivitetssted[LANGUAGE_NONE][0]['tid'] = 3223;
  }

  // Betaling for aktivitet (Termreference).
  $betalingtid = Ishoj_dagsorden_aktivitet_get_term_from_name('Gratis', 'aktivitetsgebyr');
  if ($betalingtid) {
    $node->field_betaling_for_aktivitet[LANGUAGE_NONE][0]['tid'] = $betalingtid;
  }

  // Arrangør (Termreference).
  $arrangortid = Ishoj_dagsorden_aktivitet_get_term_from_name('Ishøj Kommune', 'aktivitetsarrangor');
  if ($arrangortid) {
    $node->field_arrangor[LANGUAGE_NONE][0]['tid'] = $arrangortid;
  }

  // Foto.
  $file_path = drupal_realpath('sites/all/themes/ishoj/img/diverse/moede.jpg');
  $file = (object) array(
    'uid' => 1,
    'uri' => $file_path,
    'filemime' => file_get_mimetype($file_path),
    'status' => 1,
  );
  // You can specify a subdirectory, e.g. public://foo/.
  $file = file_copy($file, 'public://');
  $node->field_os2web_base_field_image[LANGUAGE_NONE][0] = (array) $file;

  // Åbenhed (Termreference).
  $aabenhedtid = ishoj_dagsorden_aktivitet_get_term_from_name('Åben for offentligheden', 'aktivitetsaabenhed');
  if ($aabenhedtid) {
    $node->field_aabenhed[LANGUAGE_NONE][0]['tid'] = $aabenhedtid;
  }

  // Aktivitetsreference (Tekst) (nid til dagsordenen).
  $node->field_aktivitetsreference[LANGUAGE_NONE][0]['value'] = $n->nid;

  node_save($node);

  drupal_set_message(t('En node fra indholdstypen aktivitet er blevet oprettet.\n'));
}

/**
 * Helper function to dynamically get the tid from the term_name.
 *
 * @param string $term_name
 *   Term name.
 * @param string $vocabulary_name
 *   Name of the vocabulary to search the term in.
 *
 * @return bool
 *   Term id of the found term or else FALSE.
 */
function ishoj_dagsorden_aktivitet_get_term_from_name($term_name, $vocabulary_name) {
  if ($vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_name)) {
    $tree = taxonomy_get_tree($vocabulary->vid);
    foreach ($tree as $term) {
      if ($term->name == $term_name) {
        return $term->tid;
      }
    }
  }
  return FALSE;
}
